### ISSUE TITLE
bug: HierarchyRequestError

### ISSUE THREAD

**Issue by krmax44** [saberland/saber#107]
Using `saber build`, I get this error (only sometimes though) when navigating around the site. I don't get it when using just the `saber` command:

```
HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy
```

Demo: https://saber-theme-tailsaw.netlify.com
Code: https://github.com/krmax44/saber-theme-tailsaw

**Comment by egoist** [comment]
https://github.com/krmax44/saber-theme-tailsaw/pull/1 Probably we should allow to run app in SSR in dev mode, useful for debugging.

**Comment by krmax44** [comment]
Used Firefox and Chromium, same error

**Comment by MarchWorks** [comment]
I get the same error as @egoist

**Comment by egoist** [comment]
@MarchWorks does https://deploy-preview-1--saber-theme-tailsaw.netlify.com/ work for you now?

**Comment by MarchWorks** [comment]
@egoist yes
