### ISSUE TITLE
chore: Move Saber to an organization

### ISSUE THREAD

**Issue by krmax44** [saberland/saber#132]
With a growing number of themes and plugins expected to be created, it'd be nice to have them all in one place alongside the main Saber repo. That's why I'd propose transferring Saber and all related repos to an Github organization.

**Comment by egoist** [comment]
I have https://github.com/saberland

Let's start by moving some themes and plugins there, if you want to join the organization please ping me on #general channel on https://chat.saber.land

**Comment by egoist** [comment]
Done.

**Comment by krmax44** [comment]
some aftermath trouble to deal with:

 1. checks for PRs don't work
 2. circleci badge in README is broke, probably has to do with 1
 3. npm page is kinda broken
