### ISSUE TITLE
i18n: support for vue pages

### ISSUE THREAD

**Issue by MarchWorks** [saberland/saber#162]
#### What problem does this feature solve?
Translate vue pages like https://github.com/saberland/saber/blob/master/website/pages/index.vue
#### What does the proposed API look like?
N/A
#### How should this be implemented in your opinion?
N/A
#### Are you willing to work on this yourself?
PR Welcome

**Comment by egoist** [comment]
What do you mean?

**Comment by MarchWorks** [comment]
`Lang/index.vue` doesn't work

**Comment by MarchWorks** [comment]
but I haven't tried it with the last version wait a minute

**Comment by MarchWorks** [comment]
Working fine

**Comment by egoist** [comment]
btw I think we should start translating the docs when Saber is more stable, the English docs are still far from good.

**Comment by MarchWorks** [comment]
Agree
