### ISSUE TITLE
Deprecate `page.attributes` and use `page` directly

### ISSUE THREAD

**Issue by egoist** [saberland/saber#166]
#### What problem does this feature solve?

Using `page.attributes` is kinda verbose, that's 15 letters 😅, it's also pretty confusing when you want to add new properties on the `page` object, sometimes we have `page.attributes.markdownHeadings` and sometimes we have `page.posts` 😅

#### How should this be implemented in your opinion?

Assign everything to `page` directly, of course you can't override `page.internal`.

We can add `page.attributes = page` in `vue-renderer/lib/page-prop-loader.js` for backward compatibility.

#### Are you willing to work on this yourself?

Yes.

**Comment by krmax44** [comment]
If this gets implemented, a warning would be nice whenever `page.attributes` gets used. Maybe with the help of a getter or some sort of webpack/babel plugin

**Comment by egoist** [comment]
A getter should be enough I guess.

**Comment by egoist** [comment]
Closing this.

> sometimes we have `page.attributes.markdownHeadings` and sometimes we have `page.posts`

I've updated the code to inject all new properties to `page` directly instead of `page.attributes`.

**Comment by krmax44** [comment]
Shouldn't we also then be using `page.assets` instead of `page.attributes.assets`? :thinking:

**Comment by egoist** [comment]
It's probably fine to updating an existing attribute.
