### ISSUE TITLE
Run saber server on 3001 port if 3000 is being used

### ISSUE THREAD

**Issue by MarchWorks** [saberland/saber#182]
#### What problem does this feature solve?
Running saber server whiteout passing a port argument while the port 3000 is being used break the app 
#### What does the proposed API look like?
Run the server on the port 3001 automatically 
#### How should this be implemented in your opinion?
N/A
#### Are you willing to work on this yourself?
YES

**Comment by kidonng** [comment]
We already have `--port` option, this looks unnecessary somewhat.

**Comment by krmax44** [comment]
@kidonng but it's much more elegant if Saber just binds itself to an available port instead of crashing whenever 3000 is already used.

**Comment by kidonng** [comment]
Running multiple dev server is rare, it's common to show a message notifying the port is taken. Though I agree Saber shouldn't crash 😂
