### ISSUE TITLE
Line highlighting conflict with `markdown-it-attrs`

### ISSUE THREAD

**Issue by kidonng** [saberland/saber#199]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Saber use the same syntax (curly brackets `{}`) as `markdown-it-attrs` use for `highlightLines` function, thus causing a confict which make pages containing highlight lines can't render.

#### Version

0.6.2

#### Steps to reproduce

Install `markdown-it-attrs` and enable it in Saber config, then write code block using `highlightLines`, for example:

<pre>
```js { highlightLines: ['1-2', 4] }
const foo = 'bar'
const baz = () => {
  return `${1 ? true : false}`
}
```
</pre>

#### What is expected?

Page rendered normally.

#### What is actually happening?

Page isn't rendered and the browser's console show these error:

```
Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '[1-2,' is not a valid attribute name.
    at baseSetAttr (http://localhost:3000/_saber/js/client.js:17124:8)
    at setAttr (http://localhost:3000/_saber/js/client.js:17099:5)
    at Array.updateAttrs (http://localhost:3000/_saber/js/client.js:17054:7)
    at invokeCreateHooks (http://localhost:3000/_saber/js/client.js:16408:22)
    at createElm (http://localhost:3000/_saber/js/client.js:16295:11)
    at createChildren (http://localhost:3000/_saber/js/client.js:16392:9)
    at createElm (http://localhost:3000/_saber/js/client.js:16293:9)
    at createChildren (http://localhost:3000/_saber/js/client.js:16392:9)
    at createElm (http://localhost:3000/_saber/js/client.js:16293:9)
    at createChildren (http://localhost:3000/_saber/js/client.js:16392:9)
```

#### Other relevant information

- Result of running `saber -v`: cli.js/0.6.2 win32-x64 node-v12.2.0
- Browser version (optional): Chrome 76.0.3795.3
- Is Saber a global or local install? local
- Which package manager did you use for the install? Yarn
- Does this issue occur when all plugins are disabled? No

**Comment by egoist** [comment]
Maybe try https://github.com/rstacruz/markdown-it-decorate instead?

**Comment by h404bi** [comment]
Though the syntax of markdown-it-decorate looks more reliable, but the package is too old and lack of maintance.

**Comment by egoist** [comment]
A lot of activity is not always a sign of health, a well-maintained project will require far less activity, I went through its issue tracker and there're few bug reports.

With that being said, probably we should provide an alternative syntax for enabling line highlighting, for example:

````markdown

<!-- @saber-highlight-lines: [1, '3-6'] -->

```js
function foo() {


 // ...

}
```

````

**Comment by egoist** [comment]
There's a workaround actually: https://github.com/arve0/markdown-it-attrs#custom-delimiters

```js
module.exports = {
  markdown: {
    plugins: {
      resolve: 'markdown-it-attrs',
      options: { 
        leftDelimiter: '[',
        rightDelimiter: ']'
      }
  }
}
```

**Comment by egoist** [comment]
There's a workaround actually: https://github.com/arve0/markdown-it-attrs#custom-delimiters

```js
module.exports = {
  markdown: {
    plugins: {
      resolve: 'markdown-it-attrs',
      options: { 
        leftDelimiter: '[',
        rightDelimiter: ']'
      }
  }
}
```

**Comment by kidonng** [comment]
> With that being said, probably we should provide an alternative syntax for enabling line highlighting.

Vote 👍 

Thanks for mentioning custom delimiters, for now I'll just use `[]` instead.
