### ISSUE TITLE
Deprecate saber-plugin-generate-feed on npm

### ISSUE THREAD

**Issue by h404bi** [saberland/saber#200]
[saber-plugin-generate-feed](https://www.npmjs.com/package/saber-plugin-generate-feed).

FYI:
> npm deprecate saber-plugin-generate-feed@"<=0.2.4" "This module has moved and is now available at saber-plugin-feed. Please update your dependencies as this version is no longer maintained and may contain bugs and security issues."

**Comment by egoist** [comment]
Done.
