### ISSUE TITLE
Links aren't working the same in blog post as in page

### ISSUE THREAD

**Issue by spekulatius** [saberland/saber#203]
- [x] I confirm that this is an issue rather than a question.

## Bug report

I'm building a Saber site and noticed a difference between the links in the regular page templates vs. the blog post template:

In the regular pages links like this one:

![image](https://user-images.githubusercontent.com/8433587/58328491-6c440980-7e5c-11e9-9186-2ea04c1c3b01.png)

work without any issues. 👍️

If I copy the same link over into a blog post it doesn't get processed and remains as this in the output:

![image](https://user-images.githubusercontent.com/8433587/58328548-8c73c880-7e5c-11e9-81bc-64c5e73857b0.png)

Did I forget to do something or is this a bug?

#### Version

saber-blog-starter@1.0.0 /var/www/saber-blog-starter
├── prismjs@1.16.0
├── saber@0.5.4
├── saber-highlight-css@0.0.3
├── saber-plugin-feed@0.3.2
├── saber-plugin-prismjs@0.2.0
├── saber-plugin-query-posts@0.3.1
└── saber-theme-minima@3.0.1

#### Steps to reproduce

Git repo here: https://github.com/spekulatius/saber-blog-starter

Files in question:

https://github.com/spekulatius/saber-blog-starter/blob/master/pages/about.md

and

https://github.com/spekulatius/saber-blog-starter/blob/master/pages/_posts/post2.md

#### What is expected?

Having a working link - same as in the regular pages.

#### What is actually happening?

Link points to the href, without processing (see image).

#### Other relevant information

- Result of running `saber -v`: saber/0.5.4 linux-x64 node-v8.10.0
- Browser version (optional): FF 67.0
- Is Saber a global or local install? Locally
- Which package manager did you use for the install? npm
- Does this issue occur when all plugins are disabled? good question. not sure how to test this.

**Comment by krmax44** [comment]
If you change it to `./_posts/index.md`, does it work then? Also it appears that in the Git repo, the folder architecture is `_posts`, rather than `posts/_posts`.

**Comment by kidonng** [comment]
> If you change it to `./_posts/index.md`, does it work then? Also it appears that in the Git repo, the folder architecture is `_posts`, rather than `posts/_posts`.

```
/posts/_posts/index.md
  ↑             ↑
config   "./index.md" parsed
```

**Comment by egoist** [comment]
The link in your `_posts/post2.md` should be: `../index.md`

**Comment by egoist** [comment]
i.e. it's resolved from current file instead of `pages/` folder.

**Comment by spekulatius** [comment]
> The link in your `pages/_posts/post2.md` should be: `../index.md` cuz your `index.md` is in the parent folder `pages` instead of `pages/_posts`.
> 
> Saber will look for the actual file on your disk, if it exists and it's a page, it will be replaced by the permalink of the page.

Ah, okay. This explains this. I thought the path would be starting off from the `pages/` folder 👍️

Thanks for jumping in and replying :)
