### ISSUE TITLE
Convert relative links to permalinks didn't work

### ISSUE THREAD

**Issue by kidonng** [saberland/saber#205]
- [x] I confirm that this is an issue rather than a question.

## Bug report

#25 didn't work on Windows 😢.

#### Version

0.6.3

#### Steps to reproduce

Run Saber in [the repo](https://github.com/spekulatius/saber-blog-starter) from #203 (links [fixed](https://github.com/saberland/saber/issues/203#issuecomment-495639774)).

#### What is expected?

Links coverted successfully.

#### What is actually happening?

Both links in pages and posts aren't coverted, output is `/index.md`.

![image](https://user-images.githubusercontent.com/44045911/58335742-d8326c00-7e74-11e9-9ed0-37364443ab33.png)

#### Other relevant information

- Result of running `saber -v`: cli.js/0.6.3 win32-x64 node-v12.3.1
- Browser version (optional): Chrome 76.0.3800.0
- Is Saber a global or local install? local
- Which package manager did you use for the install? Yarn
- Does this issue occur when all plugins are disabled? Yes

**Comment by egoist** [comment]
Probably we need to convert back slashes to slashes here: https://github.com/saberland/saber/blob/7e32a24e45ea1559f97fee9c53a4ff702af13420/packages/saber/vue-renderer/app/create-app.js#L115

**Comment by kidonng** [comment]
Didn't helped. But thanks for the tip, I found the cause, hardcoded `/` here (on Windows it's `\`):
https://github.com/saberland/saber/blob/e596812f21aefc8b0206883f61af257bfa51b5a4/packages/saber/lib/markdown/link-plugin.js#L33

**Comment by egoist** [comment]
welp, let's slash-ify `absolutePath` then.

**Comment by kidonng** [comment]
> welp, let's slash-ify `absolutePath` then.

When `absolutePath` includes `env.pagesDir`, it is relative link, am I correct? I created a PR to remove the slash.
