### ISSUE TITLE
medium like lightbox

### ISSUE THREAD

**Issue by diomed** [saberland/saber#222]
#### What problem does this feature solve?
Would be nice if we had plugin for nice medium like display of images

#### What does the proposed API look like?
https://github.com/francoischalifour/medium-zoom

#### How should this be implemented in your opinion?
Smoothly

#### Are you willing to work on this yourself?
No

**Comment by kidonng** [comment]
I'm using the library too 😄 
It's really easy to create a plugin, just take [saber-plugin-google-analytics](https://github.com/saberland/saber/tree/master/packages/saber-plugin-google-analytics) as an example:

`index.js`

```js
const path = require('path')

const ID = 'medium-zoom'

exports.name = ID

exports.apply = (api, { selector = 'img' } = {}) => {
  api.hooks.chainWebpack.tap(ID, config => {
    config.plugin('constants').tap(([options]) => [
      Object.assign(options, {
        __MEDIUM_ZOOM_SELECTOR__: selector
      })
    ])
  })

  api.browserApi.add(path.join(__dirname, 'saber-browser.js'))
}
```

`saber-browser.js`

```js
export default function({ router }) {
  if (process.browser) {
    const mediumZoom = require('medium-zoom')

    router.afterEach(to => {
      mediumZoom(__MEDIUM_ZOOM_SELECTOR__)
    })
  }
}
```

**Comment by diomed** [comment]
@kidonng could you publish this on npm?

**Comment by kidonng** [comment]
> @kidonng could you publish this on npm?

Untested. https://www.npmjs.com/package/saber-plugin-medium-zoom

**Comment by diomed** [comment]
hmm... algolia can't find it on npm :P

**Comment by diomed** [comment]
algolia still can't find it on npm :P
