### ISSUE TITLE
Documentation for `injectMarkdownHeadings` is wrong

### ISSUE THREAD

**Issue by Morgul** [saberland/saber#262]
- [x] I confirm that this is an issue rather than a question.

## Bug report

The documentation for where the markdown headings are stored states that they are available at `page.attributes.markdownHeadings`

![image](https://user-images.githubusercontent.com/770655/59386280-df3df300-8d2b-11e9-8112-ba48af4c99cc.png)

However, if we check the [unit test][unit], we see it's `page.markdownHeaders`

[unit]: https://github.com/saberland/saber/blob/master/packages/saber/lib/markdown/__test__/headings-plugin.test.js#L21

#### Version

`v0.6.7`

#### Steps to reproduce

Simply have a default saber site, without turning off markdown header injection.

#### What is expected?

That the headers be exposed at the location specified in the documentation. 😉 

#### What is actually happening?

It is exposed under a different property.

#### Other relevant information

- Result of running `saber -v`:
  - saber/0.6.7 darwin-x64 node-v12.4.0
- Browser version (optional):
  - Chrome
- Is Saber a global or local install?
  - local
- Which package manager did you use for the install?
  - `yarn`
- Does this issue occur when all plugins are disabled?
  - yes

**Comment by kidonng** [comment]
The headings do be available at `page.attributes.markdownHeadings`, I even made a [table of contents component](https://github.com/kidonng/the-story/blob/d335f341ed3f52b748df9f1a1fb6c8fbc1a9e1f8/packages/saber-theme-aimer/components/Contents.vue#L15) using that.
You can clone the site and add `toc: true` to any post and see if table of contents is available.

**Comment by egoist** [comment]
@kidonng it looks like you're using `page.markdownHeadings` 😅

Yes the doc is wrong, it should be `page.markdownHeadings` and it's fixed now.

**Comment by Morgul** [comment]
@egoist Thanks for the fast turn-around! I was hoping the current location was the intended one; I was a little worried about collisions if they were really being stored under `page.attributes`.

**Comment by kidonng** [comment]
> @kidonng it looks like you're using `page.markdownHeadings` 😅

😂 Sorry maybe I mistook it for other things
