### ISSUE TITLE
Website: add Algolia search

### ISSUE THREAD

**Issue by egoist** [saberland/saber#284]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/saberland/saber/issues/284)

#### How should this be implemented in your opinion?

1. apply https://community.algolia.com/docsearch
2. use https://yarnpkg.com/package/vue-instantsearch

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/saber/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by MarchWorks** [comment]
Never used algolia but maybe docsearch is stronger

**Comment by egoist** [comment]
@MarchWorks docsearch is what I meant, it is powered by Algolia Search under the hood if I'm not mistaken.

**Comment by egoist** [comment]
@MarchWorks docsearch is what I meant, it is powered by Algolia Search under the hood if I'm not mistaken.

**Comment by MarchWorks** [comment]
@egoist sorry my sentence is very confusing I mean maybe it's better than vue-instantsearch
