### ISSUE TITLE
CSS optimization 

### ISSUE THREAD

**Issue by MarchWorks** [saberland/saber#287]
#### How should this be implemented in your opinion?
A plugin or maybe in the core

PS: This will be good for complicated themes

**Comment by egoist** [comment]
what exactly needs to be optimized?

**Comment by MarchWorks** [comment]
@egoist read the introduction in readme here https://github.com/css/csso
it's not something necessary that's why I added the discussion label

**Comment by egoist** [comment]
I'm not sure how is that different from cssnano which is what we currently use.

**Comment by MarchWorks** [comment]
Absolutely it's the same I should have checked package.json first. Closing this
