### ISSUE TITLE
Refactor the page interface

### ISSUE THREAD

**Issue by egoist** [saberland/saber#332]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Funded-%2300A156.svg" />](https://issuehunt.io/r/saberland/saber/issues/332)

https://saber.land/docs/page-interface.html

We should not reuse the `page.attributes` object, i.e. setting a new `page.permalink` property instead of overriding `page.attributes.permalink`

Currently the behavior is inconsistent, sometimes we use `page.attributes.permalink` the other times we use `page.excerpt` 😅

Basically we will keep `page.attributes` which is set by front matter or `export const attributes = {}`, instead of modifying `page.attributes` we should infer `page` from `page.attributes` and other information, e.g. `page.slug` is inferred from `page.attributes.slug` and the filename.

This will introduce breaking changes.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#345 feat: refactor page interface](https://issuehunt.io/r/saberland/saber/pull/345)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/saber/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by saltysugar** [comment]
Hi, can I work on this? I’ve used Saber for a few weeks and really like it.

**Comment by egoist** [comment]
Sure, if having any questions, feel free to ask.

saltysugar <notifications@github.com> 于 2019年7月21日周日 上午12:18写道：

**Comment by egoist** [comment]
Hmm I'm thinking about making this more similar to Jekyll:

- https://jekyllrb.com/docs/front-matter/
- https://jekyllrb.com/docs/variables/

The `page` variable in Jekyll is simply page specific information + front matter, i.e. custom variables set via the front matter will be available on `page`.
