### ISSUE TITLE
Feature request: disable service worker

### ISSUE THREAD

**Issue by saltysugar** [saberland/saber#350]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/saberland/saber/issues/350)

#### What problem does this feature solve?

I was using saber-plugin-pwa but now I no longer need the PWA feature.

#### What does the proposed API look like?

```yaml
- resolve: saber-plugin-pwa
  options:
    disabled: true
```

#### How should this be implemented in your opinion?

When `disabled: true`, this plugin registers a service worker to uninstall previously installed service worker.

#### Are you willing to work on this yourself?

Yes 😄

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/saber/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by krmax44** [comment]
Maybe the current service worker could be changed so that it removes itself when an update is applied without `saber-plugin-pwa`.

**Comment by Kelier** [comment]
Loop over those registrations and all the registration object's unregister function?

```
navigator.serviceWorker.getRegistrations().then(

    function(registrations) {

        for(let registration of registrations) {  
            registration.unregister();

        }

});

```
