### ISSUE TITLE
Frontmatter asset in prevPost not loading

### ISSUE THREAD

**Issue by ohiosveryown** [saberland/saber#367]
In _saber-node.js_ I have (title, date, architect and permalink all work correctly – when I add first_img, I get an error):
<img width="446" alt="01" src="https://user-images.githubusercontent.com/12748054/63228480-84a89380-c1c1-11e9-802a-31fd183520d5.png">

In the Vue file querying the posts, I have:
<img width="568" alt="02" src="https://user-images.githubusercontent.com/12748054/63228510-e2d57680-c1c1-11e9-9715-2e722e0bc7d7.png">

Which prompts the following error in the console:
![03](https://user-images.githubusercontent.com/12748054/63228519-0dbfca80-c1c2-11e9-8c7a-8d8797643c2f.png)

(front matter of the post):
<img width="312" alt="04" src="https://user-images.githubusercontent.com/12748054/63228533-58414700-c1c2-11e9-953a-6d15d8c546d7.png">

Any help would be appreciated 👍🏼

**Comment by egoist** [comment]
According to your `saber-node.js`, you should use `page.prevPost.first_img` instead of `page.prevPost.assets.first_img` 🤔

**Comment by ohiosveryown** [comment]
Knew it was going to be something silly like that 🙃 – thanks for feedback.
