### ISSUE TITLE
--lazy mode only works after refreshing the page

### ISSUE THREAD

**Issue by egoist** [saberland/saber#414]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/saberland/saber/issues/414)

#### Version

master branch

#### Steps to reproduce

- Run Saber website locally
- Open `http://localhost:3000` you will get a blank page
- Refresh and it gives you proper contents.

This only happens after we enabled SSR in dev mode.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/saber/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by saltysugar** [comment]
Caused by #404 , I will submit a fix soon. 😅
