### ISSUE TITLE
Support toc in markdown page

### ISSUE THREAD

**Issue by egoist** [saberland/saber#44]
Similar to https://vuepress.vuejs.org/guide/markdown.html#table-of-contents

Replace `[[toc]]` with the actual Table of Contents.

**Comment by MarchWorks** [comment]
@egoist should I use [markdown-it-table-of-contents](https://www.npmjs.com/package/markdown-it-table-of-contents) or should I create a new file like [VuePress tableOfContents.js](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/markdown/lib/tableOfContents.js) which way do you prefer?

**Comment by egoist** [comment]
I'm not entire sure about this now, maybe adding support for this is unnecessary since you can simply use a component directly like `<saber-toc />`

**Comment by MarchWorks** [comment]
Agree me too I don't fell like it's necessary at all, it should fall under the category of `saber-componants` repository ( Doesn't exist of course but it can in the future )

**Comment by krmax44** [comment]
I think a `saber-components` repo, a section on the website, added as an examples folder or whatever would be a great resource for beginners.

**Comment by MarchWorks** [comment]
Closing this because it's absolutely unnecessary now

**Comment by sustained** [comment]
@MarchWorks You said that this is unnecessary now, how come?

I was just about to make my own table of contents component that takes the `markdownHeadings` and produces something like VuePress has for the sidebar but if there's some existing solution for this (couldn't find it in the docs or issues) then I'd rather use that.
