### ISSUE TITLE
Windows path issue in $saber.getPageLink

### ISSUE THREAD

**Issue by egoist** [saberland/saber#460]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/saberland/saber/issues/460)

## Bug report

https://github.com/saberland/saber/blob/ac3f80d415071186e92ffa3266ff78444500b85c/packages/saber/vue-renderer/app/create-app.js#L128-L138

In line 137 `route.meta.__relative` is a path separated by slash `/`, but `relativePath` is separated by backslash `\` on Windows (since we're using `path.join` in line 128.

#### Other relevant information

- Result of running `saber -v`: saber/0.9.0 darwin-x64 node-v10.16.2

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#464 fix: Windows path issue in $saber.getPageLink ](https://issuehunt.io/r/saberland/saber/pull/464)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/saber/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by egoist** [comment]
It would be great if we can just get rid of using `path` in the fix.

**Comment by MarchWorks** [comment]
I will just say that `relativePath.replace(/\\/g, '/')` fix the problem
