### ISSUE TITLE
'Window is not defined' where to place client-side only scripts?

### ISSUE THREAD

**Issue by ohiosveryown** [saberland/saber#466]
I'm trying to use a third-party plugin (flickity) but I'm getting an error when the app tries to build: `window is not defined`. I initialized the plugin on the mount lifecycle fwiw.

I'm guessing this is because saber/vue is trying to run the plugin while rendering to the page on the server.

Any thoughts?

**Comment by egoist** [comment]
You probably need to `require` it in `mounted` as well.

**Comment by ohiosveryown** [comment]
hmm, still getting `ReferenceError: window is not defined`

**Comment by ohiosveryown** [comment]
Going to try and roll my own instead of using a third-party.
