### ISSUE TITLE
mini-css-extract-plugin run during yarn dev

### ISSUE THREAD

**Issue by pxwee5** [saberland/saber#473]
## Bug report
Setting `extractCSS` will not show any css rules in development.

#### Steps to reproduce

1. Set `build.extractCSS` to true
1. yarn dev
1. Style missing.

![image](https://user-images.githubusercontent.com/14123790/65598509-b518f400-dfef-11e9-9fac-02f7799c6aaf.png)

At [config.css.js](https://github.com/saberland/saber/blob/master/packages/saber/lib/plugins/config-css.js), `vue-style-loader` should be run on development and `mini-css-extract-plugin` should be run on production.

**Comment by egoist** [comment]
I tested in https://github.com/saberland/saber/tree/master/examples/extract-css and it works (css is extracted into a single file).

**Comment by MarchWorks** [comment]
closed with 1cc0757136698c30d4021a9b3c773983fb6a1253
