### ISSUE TITLE
How can I customize the builtin markdown anchor plugin

### ISSUE THREAD

**Issue by h404bi** [saberland/saber#48]

**Comment by egoist** [comment]
the builtin anchor plugin only add `id` attribute to the header, so I guess you can just use your own anchor plugin instead.

**Comment by egoist** [comment]
we should probably expose more options to customize builtin markdown plugins though.

**Comment by krmax44** [comment]
The anchor plugin now is the headings plugin, for which docs have been added recently: https://saber.land/docs/saber-config.html#headings
