### ISSUE TITLE
Email link gets parsed as relative link

### ISSUE THREAD

**Issue by andreasvirkus** [saberland/saber#485]
#### Steps to reproduce

Insert a `mailto:` link in a markdown file, e.g.
```
Send me an [e-mail](mailto:some@email.com)
```
Repl: https://codesandbox.io/s/saber-email-link-qb07d

#### What is expected?
The rendered HTML link should be
```
Send me an <a href="mailto:some@email.com">e-mail</a>
```

#### What is actually happening?
The root domain is added before the link
```
Send me an <a href="https://current-domain.com/mailto:some@email.com">e-mail</a>
```

#### Other relevant information

- Result of running `saber -v`: `0.9.1`
- Does this issue occur when all plugins are disabled? Yes

**Comment by egoist** [comment]
This is fixed during a refactor, will be available in next release soon.

**Comment by egoist** [comment]
Fixed in v0.10.0

**Comment by gaoryrt** [comment]
or just use `[e-mail](mailto://some@email.com)`

**Comment by andreasvirkus** [comment]
@gaoryrt any reference that that is valid html?

**Comment by gaoryrt** [comment]
It just open a new email window send to `//some@email.com`,
the double slash (`//`) won't be considered as a relative link,
which lead to this bug.

**Comment by andreasvirkus** [comment]
Okay, thanks. I wouldn't bet my money on all e-mail clients parsing that correctly though.
