### ISSUE TITLE
Add Saber to Wappalyzer

### ISSUE THREAD

**Issue by egoist** [saberland/saber#510]
Wappalyzer is a cross-platform utility that uncovers the technologies used on websites.

https://www.wappalyzer.com/docs#new-application

A typical Saber app has `<meta name="generator" content="Saber vx.y.z">` and `<div id="_saber"></div>`

**Comment by tyankatsu0105** [comment]
I'm Wappalyze user.
I'll work on this issue :)

**Comment by egoist** [comment]
Wow thanks @tyankatsu0105 🎉
