### ISSUE TITLE
Setting default document title and meta description

### ISSUE THREAD

**Issue by egoist** [saberland/saber#555]
#### What problem does this feature solve?

Adding default `<title>` and `<meta name="description">` based on `siteConfig.title` and `siteConfig.description` in your Saber config file.

#### How should this be implemented in your opinion?

Adding them to root Vue instance: https://github.com/saberland/saber/blob/a485cf80b8267ece7f25e59706a260e26130105a/packages/saber/vue-app/create-app.js#L43

**Comment by the94air** [comment]
That's a good idea. We probably do that on every application!

**Comment by M1seRy** [comment]
@egoist  Hi,  I wanna try to contribute code for this feature  : )

**Comment by egoist** [comment]
@M1seRy 👬 Let's do it

**Comment by M1seRy** [comment]
@egoist check [#pr556](https://github.com/saberland/saber/pull/556) .

 It is always nice to try new things, it's my first time to use Saber ( writing my blog with Hexo before), I really looking forward to doing more things for this project ❤️.
