### ISSUE TITLE
Feature request: Expose line number index for color highlighting

### ISSUE THREAD

**Issue by Apostolique** [saberland/saber#600]
#### What problem does this feature solve?

It makes it possible to start the lines numbers to something else than 1.

#### What does the proposed API look like?

Exposed in a similar way to the current line highlighting in the markdown.

#### How should this be implemented in your opinion?

https://github.com/saberland/saber/blob/ec2cbac5a093edbe7454f14a0cfd1af6276c1ab3/packages/saber/src/markdown/highlight-plugin.js#L66

#### Are you willing to work on this yourself?

I could if no one else does.

**Comment by egoist** [comment]
We are using CSS counters in [saber-highlight-css](https://github.com/saberland/saber/blob/ec2cbac5a093edbe7454f14a0cfd1af6276c1ab3/packages/saber-highlight-css/default.css#L74), so probably we need to inline that style into this line instead:

https://github.com/saberland/saber/blob/ec2cbac5a093edbe7454f14a0cfd1af6276c1ab3/packages/saber/src/markdown/highlight-plugin.js#L14

Like this:

```html
<span aria-hidden="true" class="saber-highlight-line-numbers" style="counter-reset: linenumber 0">
```

And make that `0` customizable.
